In [145]:
import pandas as pd
import re
import numpy as np
from sklearn.model_selection import train_test_split
import snscrape.modules.twitter as sntwitter

In [146]:
t = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:LilTunechi').get_items()):
    if i>1000:
        break
    t.append([tweet.content])
tweets_df = pd.DataFrame(t)

In [147]:
tweets_df.to_csv('LilTunechi_task1.csv', index=False, header=False)

In [148]:
df = pd.read_csv('LilTunechi_task1.csv', header=None)
df.head(10)

0
0  Going 🆙 on #AmazonMusicLive stage TONIGHT!! tw...
1                                      GO PACK GO!!!
2                                                 🤙🏾
3  Tf wrong w me playin w 12 like dat?!!? Idk but...
4                                    GO PACK GO!!!!!
5             Happy Birthday Ms Linda!!!! @lindacohn
6  Jets beat the Bills   Dat man Carton bout to b...
7  RIP to the season we should’ve gotten rid of 1...
8                                    GO PACK GO!!!!!
9  Roll tide??????? Nahhhh roll one tf up for dem...

In [149]:
def removing_emojis(tweet):
    regrex_pattern = re.compile(pattern = "["
                u"\u23cf"
                u"\u23e9"
                u"\u231a"
                u"\u3030"
                u"\ufe0f"
                u"\u200d"
                u"\u2600-\u2B55"
                u"\u2640-\u2642"
                u"\U0001F600-\U0001F64F"  
                u"\U0001F300-\U0001F5FF" 
                u"\U000024C2-\U0001F251"
                u"\U0001f926-\U0001f937"
                u'\U00010000-\U0010ffff'
                u"\U0001F680-\U0001F6FF"
                u"\U0001F1E0-\U0001F1FF"
                u"\U00002702-\U000027B0"
                "]+", flags = re.UNICODE)
    
    return regrex_pattern.sub(r'',tweet)

In [150]:
file=open('stop_words.txt','r')
stopWords = file.read()
punct =  r'[^ \\t\w\.]'
spaces = r"\s{2,}" 
http_links = r'http\S+'
digits = r'[0-9]'
username = r'@[A-Za-z0-9_]+'
hashtags = r'#[A-Za-z0-9_]+'
www_links = r'www.\S+'


df[0]=df[0].str.lower()
df = df[0].apply(removing_emojis)
df = df.replace(to_replace = http_links, value = ' ', regex = True)
df = df.replace(to_replace = stopWords, value = '', regex = True)
df = df.replace(to_replace=  digits, value='',regex=True)
df = df.replace(to_replace = r'\"\"', value = '', regex = True)
df = df.replace(to_replace = www_links, value = ' ', regex = True)
df = df.replace(to_replace = username, value = ' ', regex = True)
df = df.replace(to_replace = hashtags, value = ' ', regex = True)
df = df.replace(to_replace = punct, value = '', regex = True)
df = df.replace(to_replace = spaces, value = ' ', regex = True)
df = df.replace(to_replace = r'\.', value = '', regex = True)

In [151]:
df=df.dropna(how='all')

In [152]:
df.head(10)

0    going on stage tonight twitch aint ready for t...
1                                           go pack go
2                                                     
3    tf wrong w me playin w like dat idk buthow bou...
4                                           go pack go
5                             happy birthday ms linda 
6    jets beat the bills dat man carton bout to be ...
7    rip to the season we shouldve gotten rid of be...
8                                           go pack go
9    roll tide nahhhh roll one tf up for dem tigers...
Name: 0, dtype: object

In [153]:
df.to_csv('LilTunechi_task2.csv', index=False, header=False)
cean_csv = pd.read_csv('LilTunechi_task2.csv')
cean_csv = cean_csv.dropna()
cean_csv.to_csv('LilTunechi_task2.csv', index=False, header=False)


In [154]:
clean_csv = pd.read_csv('LilTunechi_task2.csv')

In [155]:
clean_csv.columns = ['tweets']
clean_csv.head(10)

tweets
0  tf wrong w me playin w like dat idk buthow bou...
1                                         go pack go
2                           happy birthday ms linda 
3  jets beat the bills dat man carton bout to be ...
4  rip to the season we shouldve gotten rid of be...
5                                         go pack go
6  roll tide nahhhh roll one tf up for dem tigers...
7                                         go pack go
8                                     go pack fkn go
9           new interview with my brodie more to it

In [156]:
train, test = train_test_split(clean_csv['tweets'], test_size=0.2, shuffle=True) 

In [157]:
def vocabulary(data):
    words = []
    for i in data:
        i = str(i)
        a = i.split()
        for j in a:
            words.append(j)
    word = np.array(words)
    vocab = np.unique(word)
    return vocab

In [158]:
vocab = vocabulary(train)
print(vocab)

['a' 'aa' 'aaaaaaaaaaaaaaaaahhhhhhhhhhhhhh' ... 'z' 'zane' 'zlife']


In [159]:
def bag_of_words(data, train):
    bow = []
    vocab = vocabulary(train)
    for i in data:
        v = np.zeros(len(vocab))
        i = str(i)
        a = i.split()
        for k in a:
            not_found_vocab = True
            for j in range(len(vocab)):
                if k == vocab[j]:
                    not_found_vocab = False
                    v[j] +=1
            if not_found_vocab == True:
                v = v + 1
        bow.append(v)
    return bow

In [160]:
train_features = bag_of_words(train,train)

In [161]:
for i in range(10):
    print(train_features[i])

[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[2. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [162]:
test_features = bag_of_words(test, train)

In [163]:
for i in range(10):
    print(test_features[i])

[0. 0. 0. ... 0. 0. 0.]
[7. 7. 7. ... 7. 7. 7.]
[5. 5. 5. ... 5. 5. 5.]
[4. 4. 4. ... 4. 4. 4.]
[0. 0. 0. ... 0. 0. 0.]
[1. 1. 1. ... 1. 1. 1.]
[0. 0. 0. ... 0. 0. 0.]
[8. 8. 8. ... 8. 8. 8.]
[4. 4. 4. ... 4. 4. 4.]
[0. 0. 0. ... 0. 0. 0.]


In [164]:
vocab = vocabulary(train) #ambient dim
len(vocab)

2020